### ISSUE TITLE
details

### ISSUE THREAD

**Issue by mangaojian** [mallowigi/material-theme-jetbrains-eap#157]
![e3cd50e7-1dba-43ee-ab61-5f9de4cda380](https://user-images.githubusercontent.com/24569545/29832535-245e8f3e-8d1b-11e7-8764-ecd8041159b9.png)
Black Line

![3273f7ab-ecaa-4b8f-87e6-ef13b48eb8fc](https://user-images.githubusercontent.com/24569545/29832575-3f7032a0-8d1b-11e7-8043-e4a94ae06d82.png)
![3e3913eb-1e18-4e68-8568-f75123ddb307](https://user-images.githubusercontent.com/24569545/29832576-3f710eb4-8d1b-11e7-8e12-6a373c171019.png)
Weird Icon

![b266f6d2-8354-4f20-bb7f-e9ca47fed349](https://user-images.githubusercontent.com/24569545/29832777-db7fffa4-8d1b-11e7-8d6b-1e6172f9e196.png)
Cannot select

**Comment by mallowigi** [comment]
1. There is nothing I can do for the moment for this black line but it's in the backlog
2. Js icon has already been reduced and will be available in next update
3. Test.php uses phpunit icon in order to target tests that usually ends with XXXTest.php
4. It's not a toggle icon, it's an action that changes the tab height to the recommended height

**Comment by mangaojian** [comment]
Hopefully switch to toggle,
Now the label height is too high to take up code to read space. @mallowigi

**Comment by mallowigi** [comment]
You can set the height you want in the settings

**Comment by mangaojian** [comment]
where？I can't find it. the tab height @mallowigi

**Comment by mallowigi** [comment]
Settings > Appearance > Material Theme > Tab Height
