### ISSUE TITLE
Unique tab names

### ISSUE THREAD

**Issue by whydoidoit** [mallowigi/material-theme-jetbrains-eap#163]
IntelliJ Mac 2017.2.2 - Material Theme 0.10.2

Using NodeJS/Javascript normally the IDE would show tabs with the folder name when the filename is not unique (for instance SOME_NODE_MODULE/index.js) however with the Material Theme plugin I just see INDEX.JS for every file that is a node module - making it hard to see which tab is which.

This occurs when UPPERCASE tabs are turned on (which otherwise are really nice!).  It also occurs in the CTRL-TAB file switcher.

**Comment by mallowigi** [comment]
Yes, because AFAIK the TabTitleProviders are not cumulable, therefore the uppercase is taking priority over the TabTitleProvider given by jetbrains.

I can replicate the functionality (e.g. [INDEX] BLABLA.JS) but since the uppertabs feature is a feature not a lot of people want, I'd rather not invest resources on it.

I will take care of it after the stable release.

**Comment by mallowigi** [comment]
issued a hotfix. It's not perfect, but it should be ok

Hope this doesnt trigger bad performance though

**Comment by whydoidoit** [comment]
Seems to be working fine, thanks so much for that!
