### ISSUE TITLE
Only the currently focused tab is colored

### ISSUE THREAD

**Issue by tntmarket** [mallowigi/material-theme-jetbrains-eap#184]
### Summary

If I define custom colors for certain files, only the currently focused tab is colored.

### Expected behavior

All open tabs are colored based on their custom color. 

### Actual behavior

Only the currently open tab is colored based on it's custom color.

### Steps to reproduce

![tab color issue](https://user-images.githubusercontent.com/1150079/30989961-6fa208ea-a454-11e7-82e7-13efaa8ad526.gif)

1. Define a custom scope in "Appearance & Behavior > Scopes"
2. Use the custom scope to color tabs in "Appearance & Behavior > File Colors > Use in Editor Tabs"
3. Open a few files with a custom color

### Environment

Material Theme UI EAP: 0.12.0.3.pre

PyCharm 2017.2.3
Build #PY-172.3968.37, built on September 1, 2017
Subscription expired on September 27, 2017
JRE: 1.8.0_152-release-915-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

```xml
<application>
  <component name="MaterialThemeConfig">
    <option name="highlightColor" value="80cbc4" />
    <option name="highlightThickness" value="1" />
    <option name="wallpaperSet" value="false" />
    <option name="compactSidebar" value="true" />
    <option name="statusBarTheme" value="false" />
    <option name="tabsHeight" value="30" />
    <option name="isCompactStatusBar" value="true" />
    <option name="defaultBackground" value="https://raw.githubusercontent.com/mallowigi/material-theme-jetbrains-eap/master/src/main/resources/themes/wall.jpg,60" />
  </component>
</application>
```

**Comment by tntmarket** [comment]
Nvm, just realized this is mentioned in the readme

**Comment by tntmarket** [comment]
Nvm nvm, I thought a solution was mentioned in the readme but I didn't find it.

**Comment by mallowigi** [comment]
I see what you mean, you're right. I remember having this discussion (with myself) on whether or not to colorize the other tabs. You see, currently other tabs are colored according to whether the IDE is in contrast mode or not. Since I wanted to have the experience of the theme for the whole IDE, having multiple colors in the tabs resulted in something pretty ugly, so I discarded it.

So yeah, if you can live without it it would be great, but if not I'll try to add a setting for this for next version :)
