### ISSUE TITLE
Frame background image keeps changing

### ISSUE THREAD

**Issue by roboslone** [mallowigi/material-theme-jetbrains-eap#43]
I have my own background image for IDE "Frame", but it's changed on every IDE restart to `https://raw.githubusercontent.com/mallowigi/material-theme-jetbrains-extended/master/src/main/resources/themes/wall.jpg`.

Please don't modify this setting if it was already modified by user.

**Comment by mallowigi** [comment]
Apparently there is a bug with "set Custom Wallpaper option" as it doesnt get saved. Taking care of it.

**Comment by mallowigi** [comment]
OK I've released a fix, it should be working now.

**Comment by roboslone** [comment]
Oh, I didn't realise there's an option for that. It probably should default to false, though.

**Comment by roboslone** [comment]
I've updated to the latest version and now it removes wallpaper set manually :(

**Comment by roboslone** [comment]
And I also can't just set "Custom Wallpaper" path because it doesn't provide a way to change opacity.

**Comment by mallowigi** [comment]
Are you sure? I tested unchecking the option and setting a new manually through the IDE and it worked... 

I will check it again...

**Comment by roboslone** [comment]
Pretty sure, yeah. Don't know if it matters, but I'm using PyCharm 2017.2 EAP (Build #PY-172.2656.2, built on May 30, 2017).

**Comment by roboslone** [comment]
By the way, did you restarted IDE after unchecking option and setting wallpaper?

**Comment by mallowigi** [comment]
You're right, it does overwrite the custom bg. I wonder what to do though, two options:
- If the user has a custom BG set (through the IDE option or through the plugin) and the option is checked, it will set the config value to this custom BG (or use the provided one if he clicks Restore), and unchecking the checkbox will remove the bg whatsoever
- If the user has a custom BG set but the option is checked, it will replace the bg with whatever the user entered in the MT options. If it is unchecked though it will leave it as is.

What do you think?

**Comment by roboslone** [comment]
Seconds options seems good. Just to clarify, in the case when user didn't check option in MT settings and set custom wallpaper (wall.png) through IDE settings wallpaper stays as wall.png with whatever opacity was set by the user through IDE settings. If, however, user does check option in MT settings, IDE settings are ignored completely.

That seems okay, but by default the option should be unchecked, so that users that already have set wallpapers through IDE won't suffer.

**Comment by mallowigi** [comment]
The thing is that most users don't know about this feature so this will look like this is something coming from the plugin. The best course of action of course would be that setting a custom BG through the IDE will also modify the material settings, but I can't do that as they don't provide an event listener for this.

Doing the second option means that I will need to store whatever value the user set while the option is off, and load this value when the option is off, and when it is on load the value the user put on the file chooser. But it may be harder to implement.

For the moment I've implemented the first option, so I will suggest to do so for the moment:
- Turn off the option
- Define a bg color through the IDE and save
- Reopen the settings: your new wallpaper and opacity should be set instead of the wallpaper I provided.
- Turn on the option and leave it like that.
- Restart the IDE and see if the values are persisted.

**Comment by roboslone** [comment]
I believe background image setting was a major feature at the time, JetBrains even posted about a thousand videos on YouTube on how to use it.

The appropriate thing for users that don't know about this feature, IMO, is advertising plugin feature through plugin changelog.

**Comment by mallowigi** [comment]
Ok I've changed the behavior a bit, so now if you disable the checkbox it will stop setting the background set in Material theme settings and you can use the IDE settings

**Comment by roboslone** [comment]
Thanks!
