### ISSUE TITLE
package icon can't recover back after git recover

### ISSUE THREAD

**Issue by boliza** [mallowigi/material-theme-jetbrains-eap#63]
![_018](https://user-images.githubusercontent.com/1076043/27507352-d5467f00-58ff-11e7-974c-814d0142aaa2.png)

![_019](https://user-images.githubusercontent.com/1076043/27507361-1c22b632-5900-11e7-84d4-7066f5beb2d3.png)
![_020](https://user-images.githubusercontent.com/1076043/27507366-41613194-5900-11e7-8e68-94f36781b9fe.png)

**Comment by mallowigi** [comment]
It's not actually a bug but rather how the project tree decorator have been implemented. Let me explain:

What I did is that when you open a file and edit it, the folders containing this file are changing to the "open" state, whether it's a regular folder, excluded folder, test folder or module folder (I didn't take packages into consideration here). As long as the file is opened, the ancestor folders will keep on being in that state. So in order to get back the package icon, you will need to close that file, and edit another file to refresh the tree.

Maybe at some point I can listen to git events, but this is rather complicated and not that important, but I will keep that in mind.
