### ISSUE TITLE
Fat status bar memory meter does not fill height

### ISSUE THREAD

**Issue by nazrhyn** [mallowigi/material-theme-jetbrains-eap#74]
![image](https://user-images.githubusercontent.com/1672405/28079861-e98b69d6-6637-11e7-9fd3-fa4d7fcf8a38.png)

I'm not sure what your intention is with the fat status bar (and it's likely not something I'll be using), but I'd expect the memory meter bar to fill the vertical height.

WIP?

**Comment by mallowigi** [comment]
Nope, remember that the intention was to mimic the Sublime theme and it has a padded statusbar as well.

I personally prefer it like that, though I can reduce the padding if it feels too much (for now I won't)

As for the widget, this is because the whole status bar is padded, not each element in particular. Remember that we are talking about padding, not height, so there is no way to do so.

Sorry you don't like it.

**Comment by mallowigi** [comment]
FYI if you look at the plugin you can also find out what features are in preparation :)

**Comment by nazrhyn** [comment]
No worries; you added the thin status bar option!
