### ISSUE TITLE
General: Roboto font is blurry at 12px

### ISSUE THREAD

**Issue by mallowigi** [mallowigi/material-theme-jetbrains-eap#87]

**Comment by nazrhyn** [comment]
I know you're going to tell me this is intentional, but this huge font on everything is not usable, IMO. I need a setting to put all the fonts back to their normal, sane, size, or there's no way I can use this.

**Comment by mallowigi** [comment]
Appearance > Override default fonts > Tahoma 12px

**Comment by nazrhyn** [comment]
I suppose I'm also saying that I don't even think this looks good as a default. Why waste so much space on font size for no reason?

**Comment by mallowigi** [comment]
Because otherwise the fonts look kind of blurry, hence the bug.

In any case according to this: https://material.io/guidelines/style/typography.html#typography-styles the recommended size is either 12 or 14px, but as I said 12px look blurry so I'm trying something new.

**Comment by nazrhyn** [comment]
One of the problems may be that 1080p desktop monitors at between 20 and 30 inches diagonal size are significantly lower DPI than most hand-held devices. A font at those sizes on a high-DPI device is going to look significantly better.

Comparing 12pt to your new default:   
![image](https://user-images.githubusercontent.com/1672405/28581413-20091442-7130-11e7-9c82-192403de7d9d.png)   
![image](https://user-images.githubusercontent.com/1672405/28577608-3983b73e-7125-11e7-89ff-860e9bf40032.png)

This is just what font anti-aliasing looks like on low DPI displays. That's using subpixel anti-aliasing, so it's slightly better than the older-style grayscale anti-aliasing, but it's never going to look as good as Roboto 12pt looks on a 300+ DPI display.

**Comment by mallowigi** [comment]
I see... well you may have a point. What about 13px?

**Comment by nazrhyn** [comment]
Many fonts, when jumping between point sizes, adjust in one direction or another. In some cases they get wider, sometimes taller, sometimes both. Looks like Roboto, between 12pt and 13pt, gets wider. Not that much of a difference there. However this size in the status bar, IMO, looks pretty comical.

Another thing is that the "Override default fonts" setting does seem to only apply to certain UI elements, so, the greater the disparity between what that affects and what it doesn't, the more disjoint it will look.

### 12pt
![image](https://user-images.githubusercontent.com/1672405/28585847-af8140d6-713f-11e7-9f9e-28709c88b703.png)   
![image](https://user-images.githubusercontent.com/1672405/28586038-6450d88c-7140-11e7-8bd2-f875a8e8579d.png)

### 13pt
![image](https://user-images.githubusercontent.com/1672405/28585902-dbfe020c-713f-11e7-9c27-6faab1f86beb.png)   
![image](https://user-images.githubusercontent.com/1672405/28585939-0187fda2-7140-11e7-835a-f14cec75a7b3.png)

I will say that (and, I apologize for bringing this in here, yet again), we are likely running up against my personal sensibilities, here, and some of the things that I find distasteful about the Material specification, in general. I think you've done a fantastic job with accommodating my (and hopefully others') perspectives on the matter with configuration options.

**Comment by mallowigi** [comment]
Looks like kind of ew yes (though in my case it looks perfectly fine, though kinda blurry).

Well I got a lot of complaints about switching to the default font to Roboto. IMO I like this font even though Tahoma or Segoa UI for Windows and Lucida Grande/PT Sans are my favorites in Mac. But since Roboto is the official font of the Material Design and, well, this is a Material Design theme (even though the Sublime plugin doesn't mention Roboto at all) I thought, might as well give it a shot.

But the blurry fonts are really weird though. I can imagine it's about hinting and something like that, and probably IntelliJ IDEA doesn't hint as good as the browser, so it's a shame really.

**Comment by nazrhyn** [comment]
Like I said in the other issue: I like Roboto. It's an attractive font. Windows font smoothing, though, is definitely not as regular and controlled as it is on Macintosh, for example. Quite often, programs handle it themselves rather than using the OS font renderer.

At this point, I'm more or less just used to the "cleartype" look (subpixel anti-aliasing), though there was a time when I forcibly disabled font smoothing across the OS because I didn't like how it looked. That time ended with the rise of fonts that are made with _only_ anti-aliasing in mind. For example:

![ugly fonts](https://i.stack.imgur.com/k2oyA.png)   
_Click this to see the full sized version so it's not rescaled._

Fonts like Arial, Tahoma, Trebuchet MS -- the fonts that came with Windows XP -- were all made with both grayscale anti-aliasing and no anti-aliasing in mind. Modern fonts just assume it. Given that, I feel like those fonts where more hinting work was put in to ensure that they looked good at every size and configuration tend to just look better overall, even _with_ anti-aliasing turned on, than their newer cousins.

I like the idea of lots of configuration. If someone wants Tahoma, or Roboto or Arial, letting them pick that is always better than not letting them, IMO.

**Comment by mallowigi** [comment]
Sure, but that's exactly what the Appearance > Override font is for. And FYI, the font applying that I'm doing is exactly the same as Jetbrains does with the option turned on. :)

**Comment by nazrhyn** [comment]
Agreed. As far as I understand, we're just talking about fonts and smoothing here, in general. You've already got my feedback on the default size.
